### ISSUE TITLE
Set the binlog_filename to Option<String>

### ISSUE THREAD

**Issue by lsk569937453** [apecloud/mysql-binlog-connector-rust#14]
https://github.com/apecloud/mysql-binlog-connector-rust/blob/81d8e694687f58da1f043fdee3ef48332a8d05d3/src/binlog_client.rs#L26
From the above code ,if the binlog_filename is empty,we will reset the binlog_filename and binlog_position.So I think the field could be Option<String>

**Comment by qianyiwen2019** [comment]
you are right, Option<String> is more rust.
but binlog_filename.is_empty() makes no big difference to  binlog_filename.is_none() .
what's more, BinlogClient is a pub struct being used in our prod, we would better not change it.
