### ISSUE TITLE
Add license file for this repo.

### ISSUE THREAD

**Issue by xring** [apecloud/mysql-binlog-connector-rust#15]
Hi

Thank you so much for your excellent contribution. We found this repository through [crates.io](https://crates.io/crates/mysql-binlog-connector-rust). On [crates.io](https://crates.io/crates/mysql-binlog-connector-rust), the `license` for the crate is declared as [MIT](https://choosealicense.com/licenses/mit) OR [Apache-2.0](https://choosealicense.com/licenses/apache-2.0). 

I'd like to develop based on your contribution, but there is **no license file** added in this source code repository, which gives me some concerns. Could you please add a license file to this code repository when it is convenient for you?

**Comment by qianyiwen2019** [comment]
done

**Comment by xring** [comment]
Thanks.
