### ISSUE TITLE
请教个问题:使用该crate 进行数据同步时,该选择哪个方式?

### ISSUE THREAD

**Issue by shanliu** [apecloud/mysql-binlog-connector-rust#16]
尝试使用该crate 实现将mysql的更改同步到es中,有两个同步方式.哪个更合理:
1.
```
 loop {
        let (header, data) = stream.read().await.unwrap();
       //在处理数据的循环中进行同步到ES中
    }
```
2. 
```
 loop {
        let (header, data) = stream.read().await.unwrap();
       //将数据保存到本地文件
    }
```
```
 在监听本地文件进行同步到ES中
```

使用方式1时:当同步循环中出现阻塞[如同步超时等],是否会对MYSQL或产生其他问题
是否有必要使用方式2先把更新落地到本地?

**Comment by qianyiwen2019** [comment]
方式1，不会对源端造成影响。

方案1 
优势：
简单，不需转存一遍

劣势：
源端 mysql binlog 可能会被过期清理（比如阿里云上默认是 7 天），如果你写入 ES 太慢，可能造成延迟太大，没同步的数据已经被清理了。

方式 2：
和 方式 1 刚好相反。

**Comment by qianyiwen2019** [comment]
> > 方案1，不会对源端造成影响。
> > 方案1 优势： 简单，不需转存一遍
> > 劣势： 源端 mysql binlog 可能会被过期清理（比如阿里云上默认是 7 天），如果你写入 ES 太慢，可能造成延迟太大，没同步的数据已经被清理了。
> > 方案2 和方案1 刚好相反。
> 
> 是不是可以理解为:同步日志不会延时超过7天的情况下,可以直接在用方案1的方式在循环中读取并写入ES?

我的建议是这样
