### ISSUE TITLE
可以支持rustls吗？openssl开发构建都太麻烦了

### ISSUE THREAD

**Issue by zemelLeong** [apecloud/mysql-binlog-connector-rust#18]
遇到报错：error: failed to run custom build command for `openssl-sys v0.9.102`

**Comment by qianyiwen2019** [comment]
openssl 确实麻烦，我看下。

**Comment by qianyiwen2019** [comment]
已经有同学 fix 了：https://github.com/apecloud/mysql-binlog-connector-rust/pull/20
